comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true

codecov:
 token: 4af13e03-39d1-45ee-bfa2-71350cbf9abf

language: R

sudo: false

cache: packages

after_success:

- Rscript -e 'covr::codecov()'
